version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: next-js-sample-with-translations
    path: ""
    text-resources:
      - path: ""
        format: nested-key-value
